### ISSUE TITLE
Crasheo de minecraft por razon desconocida al poner los mods

### ISSUE THREAD

**Issue by SansWarYT** [KuoadStaff/Kuoad-Web#1]
**Describe el problema**
Crasheo de minecraft con por razon  desconocida

**Pasos a seguir** (opcional)
Abrir el launcher, y darle a jugar con la version de forge puesta. Pum crasheo

**Capturas**
Colocalas aquí.
![image](https://user-images.githubusercontent.com/67755022/86465999-187c4300-bd33-11ea-91c9-69d047086ff5.png)
![image](https://user-images.githubusercontent.com/67755022/86466215-87f23280-bd33-11ea-8604-544a91c4d628.png)
![image](https://user-images.githubusercontent.com/67755022/86466283-a3f5d400-bd33-11ea-9035-4fdcd78ad3ee.png)

**Navegador:**
 - Browser Opera
 - Version 68.0.3618.173

**Texto adicional**
Esto no me paso con NINGUNA version de Catlak/kukoland.

**Comment by MyTroNco** [comment]
Hola, yo creo que eso sucede porque hay algun mod que hace conflicto.

**Comment by SansWarYT** [comment]
> Hola, yo creo que eso sucede porque hay algun mod que hace conflicto.
Voy a intentar entrar SIN el LessLag, pero yo sospecho del optifine  que viene con el pack esencial, ya que no es una version estable.
