### ISSUE TITLE
No me aparece kukoland

### ISSUE THREAD

**Issue by SansWarYT** [KuoadStaff/Kuoad-Web#3]
**Describe el problema**
No me aparece el servidor de kukoland, a pesar de haber puesto el servidor en la lista y haber activado.

**Pasos a seguir** (opcional)
Describe concretamente, que hiciste.

**Capturas**
Colocalas aquí.
![image](https://user-images.githubusercontent.com/67755022/86476909-b8dc6280-bd47-11ea-92b8-434088e20ec2.png)

**Navegador:**
 - Browser Opera
 - Version [e.g. 22](opcional)

**Texto adicional**
No se porque pasa esto, si podria conseguir ayuda inmediata seria de lo mejor, Gracias!

**Comment by KuoadStaff** [comment]
Hola, buenas SansWarYT ❤️
Este problema puede suceder, por la IP; comprueba que sea la original. En [Kukoland]( https://plaicard.wixsite.com/kuoad/kukoland)
Si sigue sin funcionar, descarga el .bat que un administrador, con la compra de la tuvo que dar.

Un saludo, Ana 😘

**Comment by SansWarYT** [comment]
Hola, buenas Ana, La ip es la original, y el .bat ya lo hice con MajokGG
De verdad, no se que pasa, pero no es mi culpa porque las 2 cosas las hice pero sigue sin funcionar, voy a probar a poner la ip de nuevo, a ver si eso lo corrige.

**Comment by KuoadStaff** [comment]
Hola, SansWarYT.
No conozco a MajokGG, ¿será un administrador? Supongo que sí.
Por favor, escriba al administrador la **Clave de Recuperación**, al "MajokGG".

Un saludo.

**Comment by SansWarYT** [comment]
MajokGG es Cristian jaja

**Comment by KuoadStaff** [comment]
Hola buenas tardes, **SansWarYT**
Es un error por culpa del firewall del equipo. Lo solucionaremos, en una hora.
¡Gracias por reportar el error!

Un saludo, **Miguel**
