### ISSUE TITLE
Pago pausado de prime

### ISSUE THREAD

**Issue by SansWarYT** [KuoadStaff/Kuoad-Web#4]
**Describe el problema**
No se la verdad que paso, lo unico que se es que entre a discord y aparecio que mi pago fue pausado y me dijo que hable con vosotros

**Capturas:**
![image](https://user-images.githubusercontent.com/67755022/86531823-d4b94300-bec4-11ea-8634-0d1c73dca2c2.png)

**Navegador:**
 - Browser Opera
 

**Texto adicional**
A mi me parece que quereis que pague de nuevo el prime, aunque no haya pasado un mes.

**Comment by KuoadStaff** [comment]
Hola **SansWarYT**,
Este error ocurre automáticamente si no recibimos el dinero del pago. Por ello, mira la actividad de tu pago que hiciste (paypal o tarjeta de crédito/débito) y comprueba el pago si fue completo o no.
Ejemplo: Pago de Kuoad por banco BBVA

Cuando compruebes si tu pago aparece que fue quitado de tu cuenta, escríbenos por aquí.
*No nos pases datos privados, como el nombre de tu banco. Gracias.

Un saludo, **Luis**

**Comment by SansWarYT** [comment]
Si no recibiis el dinero no se la razon, pero yo HE pagado los 3 euros.

**Comment by KuoadStaff** [comment]
Tranquilo **SansWarYT**,
**Necesitamos el informe digital de compra**. Para reanudar tu **Prime**
Si no, colocaste mal los datos del pago; razón que se daría suspensión de la cuenta, por "robar" a un anónimo.

**Comment by SansWarYT** [comment]
![image](https://user-images.githubusercontent.com/67755022/86533066-bb1cf900-bece-11ea-909f-b44fa26f4c23.png)
Imagen copiada de discord. Hecha en telefono. (La hago en el telefono porque no tento la aplicacion del banco digital, la pase a Cris/MajokGG y la copie)

**Comment by SansWarYT** [comment]
![image](https://user-images.githubusercontent.com/67755022/86533106-f91a1d00-bece-11ea-90f2-765a840be93a.png)
Copiada de Discord, Hecha en telefono. (La hice en el telefono la pase a cris para que tambien lo vea, la copie y la puse aca.)

**Comment by KuoadStaff** [comment]
**¡COMPRA COMPLETADA!**
Muchas gracias, tus beneficios volverá en unos momentos.

Gracias por contar con **Kuoad**.
Un saludo, **Luis**
