### ISSUE TITLE
no puedo entrar a DonuTCraft

### ISSUE THREAD

**Issue by alexandros007** [KuoadStaff/Kuoad-Web#5]
acababa de entrar al server, vi que activaron el modo premium, lo active sabiendo que yo soy premium, hago lo que me pide, pongo el /premium luego salgo del servidor y ya no me deja entrar 
![image](https://user-images.githubusercontent.com/34277998/87245017-0d679800-c442-11ea-8ac1-3b7e63e0a40b.png)

**Comment by alexandros007** [comment]
ya se soluciono

**Comment by KuoadStaff** [comment]
Hola **alexthebigone**,
Sentimos ese problema, por el momento no funciona correctamente, como pudiste experimentar. Tu cuenta está activada de nuevo.
